#!/bin/bash
#if [ $2 == 'orb' ]; then
#  ./orb ../../2011_09_26/2011_09_26_drive_0001_extract/image_00/data/%010i.png
#elif [ $2 == 'sift' ]; then
#  ./sift ../../2011_09_26/2011_09_26_drive_0001_extract/image_00/data/%010i.png
#elif [ $2 == 'surf' ]; then
#  ./surf ../../2011_09_26/2011_09_26_drive_0001_extract/image_00/data/%010i.png
#fi

./test $1/%010i.png
